from enum import Enum
class ConnectionState(str, Enum):
    DISCONNECTED='DISCONNECTED'; CONNECTING='CONNECTING'; CONNECTED='CONNECTED'; VEHICLE_DETECTED='VEHICLE_DETECTED'; READY='READY'; LOST='LOST'; RECONNECTING='RECONNECTING'; ERROR='ERROR'
